<?php
if(!isset($_SESSION))
{
   session_start();
}
if ($_SESSION['logado']):
?>	
Olá <b><?php echo $_SESSION['login']?></b>, para sair do painel administrativo <a href="sair"><button type="button" class="btn btn-default">clique aqui.</button></a>
<br>
<?php
else:
header("Location: login");
endif;
?>

<br> 
<div class="col-md-2">
    <div class="menuLateral">
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a href="/inicia-sessao" class="nav-link">
                <i class="fa fa-home"></i><span class='glyphicon glyphicon-home'></span> Painel Inicial</a>
            </li> 
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-user'></span>
               Gerenciar Usuários<span class="caret"></span></a>
                 <ul class="dropdown-menu">
                 <li class="nav-item">
              <a class="btn bg-success text-white" href="/usuario-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar Usuários</a>
            </li>
            <li class="nav-item">
                <a class="btn bg-success text-white" href="/usuario" role="button">Alterar/Deletar Usuários</a>
            </li>
              
         </ul>
            
            </li>
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-retweet'></span>
               Gerenciar Acessos<span class="caret"></span></a>
                 <ul class="dropdown-menu">
                 <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar tipos de Acesso</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso" role="button">Alterar/Deletar Acesso</a>
            </li>
              
                    </ul>
            
            </li>
                  <li class="dropdown" >
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-file'></span>
                    Gerenciar Categorias<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                          <li class="nav-item">
                                <a class="btn bg-success text-white" href="/cate" role="button">
                                <i></i>&nbsp;Categoria</a>
                          </li>
                          <li class="nav-item">
                            <a class="btn bg-success text-white" href="/cate-cadastrar" role="button">Cadastrar Categorias</a>
                          </li>
                        </ul>
                  </li>           
                <li class="dropdown" >
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-log-in'></span>
                  Gerenciar materiais<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="nav-item">
                          <a class="btn bg-success text-white" href="/material" role="button">
                            <i></i>&nbsp;Editar Deletar</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn bg-success text-white" href="/material-cadastrar" role="button">Material Cadastrar</a>
                        </li>
                  
                        </ul>
                
                  </li>

           
                <li class="nav-item">
                
                  <a href="cliente" class="nav-link"><span class='glyphicon glyphicon-envelope'></span> Mensagens do Cliente</a>
                </li>      
         </ul>
         
          
    </div>
</div>
        <div class="col-md-10">
            <h3 align="center">Relação de usuários</h3>
            <table class="table table-striped table-hover table-bordered">
                <tr>        
                    <td>Nome</td>
                    <td>Matricula</td>
                    <td>Cargo</td>
                    <td>E-mail</td>
                    <td>Tipo de Acesso</td>
                    <td>Ativo</td>
                    <td>Ações</td>
                </tr> 

                <?php 
                /* $this->view->usuarios é o array de usuarios que foi passado pelo Controller, *após a excução do método select();
                * Através do foreach, é percorrido todo o array para fazer a impressão dos dados
                */ 

                // calcula o numero de linhas retornadas pelo Select que filtou conforme pelo $inico e $itens por pagina
                
                  //Exibe os Valores na tela
                  foreach ($this->view->usuarios as $usuario):
                    foreach ($this->view->acessos as $acesso){
                      if (($usuario["Id_acesso"])==($acesso["Id_acesso"])){
                        $descricao_acesso=$acesso["nome_nivel"];
                      }

                    }
                  ?>
                  <tr>
                      <td><?php echo $usuario["primeiro_nome"]; ?></td>
                      <td><?php echo $usuario["siape"]; ?></td>
                      <td><?php echo $usuario["cargo"]; ?></td>
                      <td><?php echo $usuario["email"]; ?></td>
                      <td><?php echo $descricao_acesso; ?></td>
                      <td><?php echo $usuario["ativo"]; ?></td>
                      <td>
                          <a href="usuario-editar/<?php echo $usuario["id_usuario"]; ?>"><span class='glyphicon glyphicon-pencil'></span></a>
                          <a href="usuario-deletar-confirmacao/<?php echo $usuario["id_usuario"]; ?>"><span class='glyphicon glyphicon-remove'></span></a>
                      </td>
                    </tr>
                    <?php endforeach;
                  ?>
            </table>
            
                  
                
                </li>
              </ul>
            </nav>   
        </div>
      </div>
    </div>
  </div>

