<div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form action="usuarioLogin" method="post">
            <div class="form-group">
              <label>E-mail</label>
              <input type="email" name="email" class="form-control" placeholder="Digite o e-mail cadastrado no sistema" >
            </div>
            <div class="form-group">
              <label>Senha</label>
              <input type="password" name="senha" class="form-control" placeholder="Senha"> </div>
            <button type="submit" class="btn btn-primary">Entrar</button>
          </form>
        </div>
      </div>
    </div>
</div>