

 
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="card text-black p-2 bg-light" >
            <div class="card-body m-0">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/login.png" >
              <h4 align="center" style="color: blue" class="mb-2"><span class="fa fa-key" aria-hidden="true"> A sua senha foi cadastrada!</h4></span>
              <br>
              <div style="float:right;">
              <a class="btn btn-primary" href="/">Fazer Login</a>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
  