

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

 

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">

    <!-- Estilos de sua aplicação. Use o arquivo CSS abaixo para aplicar o estilo. Todos os arquivos referentes ao layout precisam estar no diretório public -->
  


    <!-- bjqs.css contains the *essential* css needed for the slider to work -->
    <link rel="stylesheet" href="bjqs.css">

    <!-- some pretty fonts for this demo page - not required for the slider -->
    <link href='http://fonts.googleapis.com/css?family=Source+Code+Pro|Open+Sans:300' rel='stylesheet' type='text/css'> 

    <!-- load jQuery and the plugin -->
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="js/bjqs-1.3.min.js"></script>

    <link rel="stylesheet" type="text/css" href="css/bootstrap.css"/>
    <link href="css/style.css" rel="stylesheet">



 
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="card text-black p-2 bg-light" >
            <div class="card-body m-0">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/login.png" >
              <h4 align="center" style="color: blue" class="mb-2"><span class="fa fa-key" aria-hidden="true"> A sua senha foi cadastrada!</h4></span>
              <br>
              <div style="float:right;">
              <a class="btn btn-primary" href="/">Fazer Login</a>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
    <!-- /.main-wrapper -->
  