


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

  


 

<body class="">
  
 
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="card text-black p-2 bg-light" >
            <div class="card-body m-0">
              <h4 align="center" style="color: red" class="mb-2"><span class="fa fa-key" aria-hidden="true"> Erro ao alterar senha, chave de acesso incorreta!</h4></span>
              <br>
              <div style="float:right;">
              <a class="btn btn-primary" href="/login-recuperar-senha">Tentar novamente</a>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
   