<?php
if(!isset($_SESSION))
{
   session_start();
}
if ($_SESSION['logado']):
?>	
Olá <b><?php echo $_SESSION['login']?></b>, para sair do painel administrativo <a href="sair"><button type="button" class="btn btn-default">clique aqui.</button></a>
<br>
<?php
else:
header("Location: login");
endif;
?><br> 
<div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/cliente" role="button">
                <i></i>&nbsp;Mensagens</a>
            </li>
            
          </ul>
        </div>
      </div>
    </div>
  </div>
        <div class="col-md-2">
<ul class="nav nav-pills flex-column">
          <li class="nav-item">
              <a href="/inicia-sessao" class="nav-link">
                <i class="fa fa-home"></i>&nbsp;Painel Inicial</a>
            </li>            
            <li class="nav-item">
              <a href="usuario" class="nav-link">Gerenciar usuários</a>
            </li>
            <li class="nav-item">
              <a href="acesso" class="nav-link">Gerenciar acessos</a>
            </li>            
            <li class="nav-item">
              <a href="cate" class="nav-link">Gerenciar categorias</a>
            </li>            
            <li class="nav-item">
              <a href="material" class="nav-link">Gerenciar Material</a>
            </li>
            <li class="nav-item">
              <a href="cliente" class="nav-link">Mensagens do Cliente</a>
            </li>  
          </ul>
</div>

<div class="col-md-10">
<h4>Relação de clientes</h4>
<table class="table table-striped table-hover table-bordered">
    <tr>        
        <td>Nome</td>
        <td>E-mail</td>
        <td>Descrição</td>
        <td>Ações</td>
    </tr> 
    <?php 
    /* $this->view->clientes é o array de clientes que foi passado pelo Controller, *após a excução do método select();
    * Através do foreach, é percorrido todo o array para fazer a impressão dos dados
    */ 
    foreach ($this->view->clientes as $cliente): 
    ?>
    <tr>
        <td><?php echo $cliente["nome"]; ?></td>
        <td><?php echo $cliente["email"]; ?></td>
        <td><?php echo $cliente["descricao"]; ?></td>
        <td>
            <a href="cliente-editar/<?php echo $cliente["id"]; ?>"><span class='glyphicon glyphicon-pencil'></span></a>
            <a href="cliente-deletar-confirmacao/<?php echo $cliente["id"]; ?>"><span class='glyphicon glyphicon-remove'></span></a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
</div>