<div class="jumbotron">
        <h1><img srcset="img/logo.jpg" media="min-width: 300px">Construir sem Grilos</h1>
       
        
  
  <div class="info">
    <aside>
    <p>Contato</p>
    
    </aside>

  </div>


<h4>Mande sua dúvida</h4>
<form action="cliente-cadastrar-salvar" method="post">   
    <div class="form-group">
        <label>Nome: </label>        
        <input type="text" name="nome" class="form-control"> 
    </div>
    <div class="form-group">
        <label>E-mail: </label>    
        <input type="email" name="email" class="form-control"> 
    </div>
    <div class="form-group">
        <label>Coloque sua dúvida, solicitação ou crítica</label>      
        <textarea name="descricao" id="descricao"></textarea>
    </div>    
    <button type="submit" class="btn btn-success">Submeter</button>
</form>