<?php
if(!isset($_SESSION))
{
   session_start();
}
if ($_SESSION['logado']):
?>	
Olá <b><?php echo $_SESSION['login']?></b>, para sair do painel admnistrativo <a href="sair"><button type="button" class="btn btn-default">clique aqui.</button></a>

<?php
else:
header("Location: login");
endif;
?> 


<h4>Concluído</h4>
<p>O cliente foi editado com sucesso.</p><br />
<p><a href="/cliente" class="btn btn-success">Voltar para a relação de clientes</a></p>