<?php
if(!isset($_SESSION))
{
   session_start();
}
if ($_SESSION['logado']):
?>	
Olá <b><?php echo $_SESSION['login']?></b>, para sair do painel administrativo <a href="sair"><button type="button" class="btn btn-default">clique aqui.</button></a>
<br>
<?php
else:
header("Location: login");
endif;
?> <br>
<div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/material" role="button">
                <i></i>&nbsp;Material listar editar deletar</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/material-cadastrar" role="button">Material Cadastrar</a>
            </li>
            
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="col-md-2">
<ul class="nav nav-pills flex-column">
          <li class="nav-item">
              <a href="/inicia-sessao" class="nav-link">
                <i class="fa fa-home"></i>&nbsp;Painel Inicial</a>
            </li>            
            <li class="nav-item">
              <a href="usuario" class="nav-link">Gerenciar usuários</a>
            </li>
            <li class="nav-item">
              <a href="acesso" class="nav-link">Gerenciar acessos</a>
            </li>            
            <li class="nav-item">
              <a href="cate" class="nav-link">Gerenciar categorias</a>
            </li>            
            <li class="nav-item">
              <a href="material" class="nav-link">Gerenciar Material</a>
            </li>
            <li class="nav-item">
              <a href="cliente" class="nav-link">Mensagens do Cliente</a>
            </li>  
          </ul>
</div>

<div class="col-md-10">
<h4>Cadastro de Materiais</h4>
<form action="material-cadastrar-salvar" method="post" enctype="multipart/form-data">   
    <div class="form-group">
        <label>Nome do material: </label>        
        <input type="text" name="nome" class="form-control"> 
    </div>
    <div class="form-group">
        <label>Descrição: </label>      
        <textarea name="descricao" id="descricao"></textarea>
    </div>
    <div class="form-group">
        <label>Categoria: </label>    
        <select class="form-control" name="categoria">
            <?php
            foreach ($this->view->categorias as $categoria) {
                echo "<option value='".$categoria["id_categoria"]."'>".$categoria["nome"]."</option>";
            }
            ?>          
            

        </select>
    </div>
    <div class="form-group">
        <label>imagem: </label>    
        <input type="file" name="imagem" class="form-control"> 
    </div>    
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>
</div>