<?php
if (!isset($_SESSION)) {
    session_start();
}
if ($_SESSION['logado']):
?>
Olá <b><?php echo $_SESSION['login'] ?></b>, para sair do painel administrativo <a href="sair"><button type="button" class="btn btn-default">clique aqui.</button></a>
<br>
<?php
else:
    header("Location: login");
endif;
?> <br>

   <nav class="col-md-2 "> 
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
              <a href="/inicia-sessao" class="nav-link">
                <i class="fa fa-home"></i><span class='glyphicon glyphicon-home'></span> Dashboard</a>
            </li> 
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-user'></span>
               Gerenciar Usuários<span class="caret"></span></a>
                 <ul class="dropdown-menu">
                 <li class="nav-item">
              <a  href="/usuario-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar Usuários</a>
            </li>
            <li class="nav-item">
                <a  href="/usuario" role="button">Alterar/Deletar Usuários</a>
            </li>
              
         </ul>
            
            </li>
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-retweet'></span>
               Gerenciar Acessos<span class="caret"></span></a>
                 <ul class="dropdown-menu">
                 <li class="nav-item">
              <a href="/acesso-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar tipos de Acesso</a>
            </li>
            <li class="nav-item">
              <a href="/acesso" role="button">Alterar/Deletar Acesso</a>
            </li>
              
                    </ul>
            
            </li>
                  <li class="dropdown" >
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-file'></span>
                    Gerenciar Categorias<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                          <li class="nav-item">
                                <a  href="/cate" role="button">
                                <i></i>&nbsp;Categoria</a>
                          </li>
                          <li class="nav-item">
                            <a  href="/cate-cadastrar" role="button">Cadastrar Categorias</a>
                          </li>
                        </ul>
                  </li>           
                <li class="dropdown" >
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-log-in'></span>
                  Gerenciar materiais<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="nav-item">
                          <a  href="/material" role="button">
                            <i></i>&nbsp;Editar Deletar</a>
                        </li>
                        <li class="nav-item">
                            <a  href="/material-cadastrar" role="button">Material Cadastrar</a>
                        </li>
                  
                        </ul>
                
                  </li>

           
                <li class="nav-item">
                
                  <a href="cliente" class="nav-link"><span class='glyphicon glyphicon-envelope'></span> Mensagens do Cliente</a>
                </li>      
         </ul>
         
      </nav>    
 

<div class="col-md-10">
<h4>Relação de materiais</h4>
<table class="table table-striped table-hover table-bordered">
    <tr>
        <td class="celula_fixa">Nome</td>
        <td>Descrição</td>
        <td class="celula_fixa2">Categoria</td>
        <td class="celula_fixa3">Imagem</td>
        <td class="celula_fixa4">Ações</td>
    </tr>
    <?php
/* $this->view->clientes é o array de clientes que foi passado pelo Controller, *após a excução do método select();
 * Através do foreach, é percorrido todo o array para fazer a impressão dos dados
 */
foreach ($this->view->materiais as $material):
?>

    <tr>
        <td><?php echo $material["nome_produto"]; ?></td>
        <td><?php echo $material["descricao"]; ?></td>
        <td><?php echo $material["nome"]; ?></td>
        <td><img src="/imagens/thumbs/<?php echo $material["imagem"]; ?>" alt="<?php echo $material["nome_produto"]; ?>"></td>
        <td>
            <a href="material-editar/<?php echo $material["id"]; ?>"><span class='glyphicon glyphicon-pencil'></span></a>
            <a href="material-deletar-confirmacao/<?php echo $material["id"]; ?>"><span class='glyphicon glyphicon-remove'></span></a>
        </td>
    </tr>
    <?php endforeach;?>
</table>
</div>