<!DOCTYPE html>
<html>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
          <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar tipos de Acesso</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso" role="button">Tipos de Acessos</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso" role="button">Alterar/Deletar Acesso</a>
            </li>
            <li class="dropdown">
              <a class="btn bg-success text-white dropdown-toggle" data-toggle="dropdown" href="#">Usuários
              </a>
              <ul class="dropdown-menu">
                <li><a href="usuario-cadastrar">Cadastrar Usuário</a></li>
                <li><a href="usuario">Alterar/Deletar Usuário</a></li>
                <li><a href="usuario">Listar todos Usuário</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills flex-column">
            
          </ul>
        </div>
        <div class="col-md-10">
          <h4>Concluído</h4>
          <h4 style="color: green"><p>O nível de acesso foi excluído do banco de dados.</p><br /></h4>
          <p><a href="/acesso" class="btn btn-primary">Voltar para a relação de níveis de acesso</a></p>
        </div>
      </div>
    </div>
  </div>
  </html>
    
