<!DOCTYPE html>
<html>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="btn bg-success text-white" href="acesso-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar tipos de Acesso</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso" role="button">Tipos de Acessos</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso" role="button">Alterar/Deletar Acesso</a>
            </li>
            <li class="dropdown">
              <a class="btn bg-success text-white dropdown-toggle" data-toggle="dropdown" href="#">Usuários
              </a>
              <ul class="dropdown-menu">
                <li><a href="usuario-cadastrar">Cadastrar Usuário</a></li>
                <li><a href="usuario">Alterar/Deletar Usuário</a></li>
                <li><a href="usuario">Listar todos Usuário</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a href="usuario" class="nav-link">Usuários</a>
            <li class="nav-item">
              <a class="nav-link" href="portaria">Portarias</a>
            </li>
            </li>
            <li class="nav-item">
              <a href="assinatura" class="nav-link">Assinaturas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="relatorio" class="nav-link">Relatórios
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="assunto" class="nav-link">Assuntos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="subassunto" class="nav-link">Subassuntos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="tema" class="nav-link">Temas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="subtema" class="nav-link">Subtemas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="template" class="nav-link">Padrões de Formatação
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="servidor" class="nav-link">Servidores
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="aluno" class="nav-link">Alunos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="entidade" class="nav-link">Instituições
                <br> </a>
            </li>
          </ul>
        </div>
        <div class="col-md-10">
            <h3>Informações salvas</h3>
            <h4 style="color: red"><p>O acesso não foi salvo no banco de dados.</p></h4><br>
            <div class="row">
              <div class="col-md-3">
               <a class="btn btn-success"" href="acesso">Relação de acessos</a>
              </div>
            <div class="col-md-3">
              <a align="center" class="btn btn-secondary" href="acesso-cadastrar">Cadastrar novamente</a>
            </div>
           </div>
         </div>
       </div>
     </div>
   </div>
</html>