<!DOCTYPE html>
<html>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar tipos de Acesso</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso" role="button">Tipos de Acessos</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/acesso" role="button">Alterar/Deletar Acesso</a>
            </li>
            <li class="dropdown">
              <a class="btn bg-success text-white dropdown-toggle" data-toggle="dropdown" href="#">Usuários
              </a>
              <ul class="dropdown-menu">
                <li><a href="usuario-cadastrar">Cadastrar Usuário</a></li>
                <li><a href="usuario">Alterar/Deletar Usuário</a></li>
                <li><a href="usuario">Listar todos Usuário</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills flex-column">
            
          </ul>
        </div>
        <div class="col-md-10">
        <?php
          // Retorna o ID passado por parâmetro na URL.
          // Este id será enviado à URL cliente-deletar-salvar/id
           
          $url = parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);
          $pieces = explode("/", $url);
          $id = $pieces[2];
          ?>
    		<br>
    		<h4>Você está prestes a deletar um nível de acesso. Você tem certeza?</h4>
    		<h4 style="color: red"><p>Esta ação não poderá ser desfeita. </p><p>Deseja continuar?</p><br /></h4>
    		<p>
          <a href="/acesso-deletar-salvar/<?php echo $id; ?>" class="btn btn-success">Sim</a>
          <a href="/acesso" class="btn btn-danger">Não</a> 
        </p>
      </div>
    </div>
  </div>
</div>
</html>
