<!DOCTYPE html>
<html>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/status-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar Status</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/status" role="button">Listar Status</a>
            </li>
            <li class="nav-item">
                <a class="btn bg-success text-white" href="/status" role="button">Alterar/Deletar Status</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="#" role="button">Versões Associadas</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a href="usuario" class="nav-link">Usuários</a>
            <li class="nav-item">
              <a class="nav-link" href="portaria">Portarias</a>
            </li>
            </li>
            <li class="nav-item">
              <a href="assinatura" class="nav-link">Assinaturas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="relatorio" class="nav-link">Relatórios
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="assunto" class="nav-link">Assuntos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="subassunto" class="nav-link">Subassuntos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="tema" class="nav-link">Temas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="subtema" class="nav-link">Subtemas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="template" class="nav-link">Padrões de Formatação
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="servidor" class="nav-link">Servidores
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="aluno" class="nav-link">Alunos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="entidade" class="nav-link">Instituições
                <br> </a>
            </li>
          </ul>
        </div>
        <div class="col-md-10">
          <h3>Informações salvas</h3>
          <h4><p>O status foi salvo no banco de dados.</p></h4>
          <div class="row">
            <div class="col-md-3">
             <a class="btn btn-success"" href="status">Relação de status</a>
           </div>
           <div class="col-md-3">
             <a align="center" class="btn btn-secondary" href="/status-cadastrar">Cadastrar outro</a>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>
 </html>