<!-- 
 <div class="col-lg-6">
    <h2>Usuario ou senha incorretos</h2>
    <p>Deseja tentar novamente</p>
    <p><a class="btn btn-success" href="login" role="button">Tentar novamente</a>   ou   <a class="btn btn-primary" href="/" role="button">Voltar para o inicio</a></p>
  </div> -->


<?php
if(!isset($_SESSION))
{
   session_start();
}
if ($_SESSION['logado']):
?>	

 <div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/usuarios.png" >
              <br>
              <a href="/usuario" class="btn btn-success">Gerenciar Usuários</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/acesso.png" >
              <br>
              <a href="/acesso" class="btn btn-success">Gerenciar Acessos</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/alunos.png" >
              <br>
              <a href="/aluno" class="btn btn-success">Gerenciar Alunos</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/servidores.png" >
              <br>
              <a href="/servidor" class="btn btn-success">Gerenciar Servidores</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/entidade.png" >
              <br>
              <a href="/entidade" class="btn btn-success">Gerenciar Instituições</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/assinatura.png" >
              <br>
              <a href="/assinatura" class="btn btn-success">Gerenciar Assinaturas</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/relatorio.png" >
              <br>
              <a href="/relatorio" class="btn btn-success">Gerenciar Relatórios</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/notificacao.png" >
              <br>
              <a href="/notificacao" class="btn btn-success">Gerenciar Notificações</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/template.png" >
              <br>
              <a href="/template" class="btn btn-success">Gerenciar Templates </a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/portaria.png" >
              <br>
              <a href="/portaria" class="btn btn-success">Gerenciar Portarias</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/status.png" >
              <br>
              <a href="/status" class="btn btn-success">Gerenciar Status</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div "card" style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/requerimento.png" >
              <br>
              <a href="/requerimento" class="btn btn-success">Gerenciar Requerimentos</a>
            </div>
          </div>
        </div>
      </div>
  </div>





 <!--<a href="sair">Sair do painel Administrativo</a>-->

<?php
else:
header("Location: login");
endif;
?> 

