
  
 
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="card text-black p-2 bg-light" >
            <div class="card-body m-0">              
              <h4 align="center" style="color: blue" class="mb-2">Cadastrar senha</h4>
              <form method="POST" action="/usuario-senha-primeiro-acesso" id="form" name="form">
              <input type="hidden" name="id_usuario" id="id_usuario" value="<?php echo$_SESSION['id_usuario'];?>">
              <input type="hidden" name="chave" id="chave" value="<?php echo$_SESSION['chave'];?>">
              <div class="form-group">
                <label for="senha">Senha</label>
                <input type="password" class="form-control" id="senha" name="senha" required>
              </div>
              <br>
              <button type="submit" class="btn btn-secondary btn-block">Cadastrar senha</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>