 <div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <div style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/usuarios.png" >
              <br>
              <a href="/usuario" class="btn btn-success">Gerenciar Usuários</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 16rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/acesso.png" >
              <br>
              <a href="#" class="btn btn-success">Gerenciar Acessos</a> <!-- acessos portarias-->
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 15rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/alunos.png" >
              <br>
              <a href="/aluno" class="btn btn-success">Gerenciar Alunos</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/servidores.png" >
              <br>
              <a href="/servidor" class="btn btn-success">Gerenciar Servidores</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/entidade.png" >
              <br>
              <a href="/entidade" class="btn btn-success">Gerenciar Instituições</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/assinatura.png" >
              <br>
              <a href="/assinatura" class="btn btn-success">Gerenciar Assinaturas</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <div style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/relatorio.png" >
              <br>
              <a href="/relatorio" class="btn btn-success">Gerenciar Relatórios</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/notificacao.png" >
              <br>
              <a href="/notificacao" class="btn btn-success">Gerenciar Notificações</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 18rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/template.png" >
              <br>
              <a href="/template" class="btn btn-success">Gerenciar Templates </a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 16rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/portaria.png" >
              <br>
              <a href="/portaria" class="btn btn-success">Gerenciar Portarias</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 15rem">
            <div class="card-body">
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/status.png" >
              <br>
              <a href="/status" class="btn btn-success">Gerenciar Status</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div style="width: 20rem">
            <div class="card-body" >
              <img class="img-fluid d-block mx-auto" src="<?php echo PATH_HOME;?>img/requerimento.png" >
              <br>
              <a href="/requerimento" class="btn btn-success">Gerenciar Requerimentos</a>
            </div>
          </div>
        </div>
      </div>
  </div>



