

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

  
  
 


  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="card text-black p-2 bg-light" >
            <div class="card-body m-0">
              <h4 align="center" style="color: red" class="mb-2"><span class="fa fa-exclamation-triangle" aria-hidden="true"> Alterar Senha </h4></span>
              <h5 align="center" style="color: red" class="mb-2">Chave de acesso incorreta, ou usuário não cadastrado!</h5><br>
              <h5 align="center" style="color: red" class="mb-2">Entre em contato com o administrador.</h5>
              <div style="float:right;">
              <a class="btn btn-primary" href="/">Sair</a>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
   