
 
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="card text-black p-2 bg-light" >
            <div class="card-body m-0">
              
              <h4 align="center" style="color: blue" class="mb-2">Login</h4>
              <form method="POST" action="/inicia-sessao" id="form" name="form">
                <div class="form-group">
                  <label for="siape">Usuário</label>
                  <input type="text" class="form-control" id="siape" name="siape" required>
                </div>
                <div class="form-group">
                    <label for="senha">Senha</label>
                    <input type="password" class="form-control" id="senha" name="senha" required>
                    <h6 align="center" class="mb-2">Esqueceu sua senha? <a href="/login-esqueceu-senha" class="mb-2">Clique aqui</a></h6>
                </div>
                  <br>
                  <button type="submit" class="btn btn-secondary btn-block">Entrar</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
  
