
  


  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="card text-black p-2 bg-light" >
            <div class="card-body m-0">
              <h4 align="center" style="color: blue" class="mb-2">Recuperar Senha</h4>
              <form method="POST" action="/login-recuperar-senha" id="form" name="form">
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" class="form-control" id="email" name="email" placeholder="Seu e-mail" required>
                  <br>
                  <button type="submit" class="btn btn-secondary btn-block">Recuperar senha</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
   

  





