
 


 
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="card text-black p-2 bg-light" >
            <div class="card-body m-0">
              <h4 align="center" style="color: blue" class="mb-2">Primeiro acesso</h4>
               <h4 align="center" class="mb-2">Seja bem-vindo!</h4>
              <form method="POST" action="/login-alterar-senha" id="form" name="form">
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" class="form-control" id="email" name="email" placeholder="e-mail cadastrado" required>
                </div>
                <div class="form-group">
                  <label for="email">Insira a Senha Provisória</label>
                  <input type="password" class="form-control" id="senha_provisoria" name="senha_provisoria" placeholder="senha provisória" required>
                </div>
                  <br>
                  <button type="submit" class="btn btn-secondary btn-block">Continuar</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>