
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

  

 

 


  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-4"> </div>
        <div class="col-md-4">
          <div class="card text-black p-2 bg-light" >
            <div class="card-body m-0">
              <h4 align="center" style="color: red" class="mb-2"><span class="fa fa-exclamation-triangle" aria-hidden="true"> Recuperar Senha</h4></span>
              <h5 align="center" style="color: red" class="mb-2">Matrícula ou email não cadastrado!</h5>
              <div style="float:right;">
              <a class="btn btn-primary" href="/">Sair</a>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
   