
  


 
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6">
          <div class="card text-black p-10 bg-light" >
            <div class="card-body m-0">
              <h4 align="center" style="color: blue" class="mb-2"><span class="fa fa-key" aria-hidden="true"> A chave de acesso foi gerada com sucessso!</h4></span>
              <br>
              <form method="POST" action="/alterar-senha-primeiro-acesso" id="form" name="form">
                <div class="form-group">
                <input type="hidden" name="chave" id="chave" value="<?php echo $chave; ?>">
                  <button type="submit" class="btn btn-secondary btn-block">Continuar</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
   





