<!DOCTYPE html>
<html>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/nivel-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar Nível</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/nivel" role="button">Listar Níveis</a>
            </li>
            <li class="nav-item">
                <a class="btn bg-success text-white" href="/nivel" role="button">Alterar/Deletar Nível</a>
            </li>
            <li class="dropdown">
              <a class="btn bg-success text-white dropdown-toggle" data-toggle="dropdown" href="#">Classe
              </a>
              <ul class="dropdown-menu">
                <li><a href="classe-cadastrar">Cadastrar Classe</a></li>
                <li><a href="classe">Alterar/Deletar Classe</a></li>
                <li><a href="classe">Listar todos Classe</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a class="btn bg-success text-white dropdown-toggle" data-toggle="dropdown" href="#">Servidor
              </a>
              <ul class="dropdown-menu">
                <li><a href="servidor-cadastrar">Cadastrar Servidor</a></li>
                <li><a href="servidor">Alterar/Deletar Servidor</a></li>
                <li><a href="servidor">Listar todos Servidor</a></li>
                <li><a href="#">Servidores Associados</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a href="usuario" class="nav-link">Usuários</a>
            <li class="nav-item">
              <a class="nav-link" href="portaria">Portarias</a>
            </li>
            </li>
            <li class="nav-item">
              <a href="assinatura" class="nav-link">Assinaturas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="relatorio" class="nav-link">Relatórios
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="assunto" class="nav-link">Assuntos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="subassunto" class="nav-link">Subassuntos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="tema" class="nav-link">Temas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="subtema" class="nav-link">Subtemas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="template" class="nav-link">Padrões de Formatação
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="servidor" class="nav-link">Servidores
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="aluno" class="nav-link">Alunos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="entidade" class="nav-link">Instituições
                <br> </a>
            </li>
          </ul>
        </div>
        <div class="col-md-10">
            <h3 align="center">Relação de Níveis</h3>
            <table class="table table-striped table-hover table-bordered">
                <tr>        
                    <td>Id Nível</td>
                    <td>Nível</td>
                    <td>Ações</td>
                </tr> 

                <?php 
                /* $this->view->niveis é o array de niveis que foi passado pelo Controller, *após a excução do método select();
                * Através do foreach, é percorrido todo o array para fazer a impressão dos dados
                */ 

                // calcula o numero de linhas retornadas pelo Select que filtou conforme pelo $inico e $itens por pagina
                $num=($this->view->niveis->rowCount());
                if ($num>0) {
                  //Exibe os Valores na tela
                  foreach ($this->view->niveis as $nivel): 
                  ?>
                  <tr>
                      <td><?php echo $nivel["Id_nivel"]; ?></td>
                      <td><?php echo $nivel["nome"]; ?></td>
                      <td>
                          <a href="nivel-editar/<?php echo $nivel["Id_nivel"]; ?>"><span class='glyphicon glyphicon-pencil'></span></a>
                          <a href="nivel-deletar-confirmacao/<?php echo $nivel["Id_nivel"]; ?>"><span class='glyphicon glyphicon-remove'></span></a>
                      </td>
                    </tr>
                    <?php endforeach;
                  }?>
            </table>
            <?php 
              //Verificar se está sendo passado na URL a página atual, senao é atribuido a pagina 
              $pagina = (isset($_GET['pagina']))? $_GET['pagina'] : 1;
              //definido no select do metodo nivelListar()
              $itens_por_pagina=11;
              // calcula o numero de linhas retornadas pelo Select com todas as linhas da tabela nivel cadastradas no banco
              $num_total=$this->view->niveis_total->rowCount();
              //definir numero de paginas
              $num_pagina = ceil($num_total/$itens_por_pagina);

              //Verificar a pagina anterior e posterior
              $pagina_anterior = $pagina - 1;
              $pagina_posterior = $pagina + 1;
            ?>
            <nav class="text-center">
              <ul class="pagination">
                <li>
                  <?php
                  if($pagina_anterior != 0){ ?>
                    <a href="nivel?pagina=<?php echo $pagina_anterior; ?>" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Previous</span>
                    </a>
                  <?php }else{ ?>
                    <span aria-hidden="true">&laquo;</span>
                <?php }  ?>
                </li>
                <?php 
                //Apresentar a paginacao
                for($i = 1; $i < $num_pagina + 1; $i++){ ?>
                  <li><a href="nivel?pagina=<?php echo $i; ?>"><?php echo $i; ?></a></li>
                <?php } ?>
                <li>
                  <?php
                  if($pagina_posterior <= $num_pagina){ ?>
                    <a href="nivel?pagina=<?php echo $pagina_posterior; ?>" aria-label="Previous">
                      <span aria-hidden="true">&raquo;</span>
                    </a>
                  <?php }else{ ?>
                    <span aria-hidden="true">&raquo;</span>
                <?php }  ?>
                </li>
              </ul>
            </nav> 
        </div>
      </div>
    </div>
  </div>
</html>
