<!DOCTYPE html>
<html>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/nivel-cadastrar" role="button">
                <i></i>&nbsp;Cadastrar Nível</a>
            </li>
            <li class="nav-item">
              <a class="btn bg-success text-white" href="/nivel" role="button">Listar Níveis</a>
            </li>
            <li class="nav-item">
                <a class="btn bg-success text-white" href="/nivel" role="button">Alterar/Deletar Nível</a>
            </li>
            <li class="dropdown">
              <a class="btn bg-success text-white dropdown-toggle" data-toggle="dropdown" href="#">Classe
              </a>
              <ul class="dropdown-menu">
                <li><a href="classe-cadastrar">Cadastrar Classe</a></li>
                <li><a href="classe">Alterar/Deletar Classe</a></li>
                <li><a href="classe">Listar todos Classe</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a class="btn bg-success text-white dropdown-toggle" data-toggle="dropdown" href="#">Servidor
              </a>
              <ul class="dropdown-menu">
                <li><a href="servidor-cadastrar">Cadastrar Servidor</a></li>
                <li><a href="servidor">Alterar/Deletar Servidor</a></li>
                <li><a href="servidor">Listar todos Servidor</a></li>
                <li><a href="#">Servidores Associados</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a href="usuario" class="nav-link">Usuários</a>
            <li class="nav-item">
              <a class="nav-link" href="portaria">Portarias</a>
            </li>
            </li>
            <li class="nav-item">
              <a href="assinatura" class="nav-link">Assinaturas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="relatorio" class="nav-link">Relatórios
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="assunto" class="nav-link">Assuntos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="subassunto" class="nav-link">Subassuntos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="tema" class="nav-link">Temas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="subtema" class="nav-link">Subtemas
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="template" class="nav-link">Padrões de Formatação
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="servidor" class="nav-link">Servidores
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="aluno" class="nav-link">Alunos
                <br> </a>
            </li>
            <li class="nav-item">
              <a href="entidade" class="nav-link">Instituições
                <br> </a>
            </li>
          </ul>
        </div>
        <div class="col-md-10">
            <h3 align="center">Cadastrar Nível</h3>
        <form action="nivel-cadastrar-salvar" method="post"> 
        <br>  
            <div class="form-group">
                <label>Nível: </label>        
                <input type="text" name="nome" class="form-control" required> 
            </div>
            <br>
            <div class="row">
               <div class="col-md-2"></div>
               <div class="col-md-2"></div>
               <div class="col-md-2">
                <a class="btn btn-danger" href="nivel">Cancelar Cadastro </a>
              </div>
              <div class="col-md-2">
                <button type="submit" class="btn btn-success">Salvar Cadastro</button>
              </div>
              <div class="col-md-2"></div>
              <div class="col-md-2"></div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
</html>
