<?php
if (!isset($_SESSION)) {
    session_start();
}
if ($_SESSION['logado']):
?>
Olá <b><?php echo $_SESSION['login'] ?></b>, para sair do painel administrativo <a href="sair"><button type="button" class="btn btn-default">clique aqui.</button></a>
<br>
<?php
else:
    header("Location: login");
endif;
?> <br> <nav class="col-md-2 "> 
<div class="sidebar-sticky">
    <ul class="nav flex-column">
        <li class="nav-item">
          <a href="/inicia-sessao" class="nav-link">
            <i class="fa fa-home"></i><span class='glyphicon glyphicon-home'></span> Dashboard</a>
        </li> 
        <li class="dropdown" >
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-user'></span>
           Gerenciar Usuários<span class="caret"></span></a>
             <ul class="dropdown-menu">
             <li class="nav-item">
          <a  href="/usuario-cadastrar" role="button">
            <i></i>&nbsp;Cadastrar Usuários</a>
        </li>
        <li class="nav-item">
            <a  href="/usuario" role="button">Alterar/Deletar Usuários</a>
        </li>
          
     </ul>
        
        </li>
        <li class="dropdown" >
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-retweet'></span>
           Gerenciar Acessos<span class="caret"></span></a>
             <ul class="dropdown-menu">
             <li class="nav-item">
          <a href="/acesso-cadastrar" role="button">
            <i></i>&nbsp;Cadastrar tipos de Acesso</a>
        </li>
        <li class="nav-item">
          <a href="/acesso" role="button">Alterar/Deletar Acesso</a>
        </li>
          
                </ul>
        
        </li>
              <li class="dropdown" >
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-file'></span>
                Gerenciar Categorias<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li class="nav-item">
                            <a  href="/cate" role="button">
                            <i></i>&nbsp;Categoria</a>
                      </li>
                      <li class="nav-item">
                        <a  href="/cate-cadastrar" role="button">Cadastrar Categorias</a>
                      </li>
                    </ul>
              </li>           
            <li class="dropdown" >
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='glyphicon glyphicon-log-in'></span>
              Gerenciar materiais<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li class="nav-item">
                      <a  href="/material" role="button">
                        <i></i>&nbsp;Editar Deletar</a>
                    </li>
                    <li class="nav-item">
                        <a  href="/material-cadastrar" role="button">Material Cadastrar</a>
                    </li>
              
                    </ul>
            
              </li>

       
            <li class="nav-item">
            
              <a href="cliente" class="nav-link"><span class='glyphicon glyphicon-envelope'></span> Mensagens do Cliente</a>
            </li>      
     </ul>
     
  </nav>    

<div class="col-md-10">

<h4>Cadastrar a categoria</h4>
<form action="cate-cadastrar-salvar" method="post">
    <div class="form-group">
        <label>Nome da categoria: </label>
        <input type="text" name="nome" class="form-control">
    </div>
   <button type="submit" class="btn btn-success">Cadastrar</button>
</form>
</div>