<?php
if(!isset($_SESSION))
{
   session_start();
}
if ($_SESSION['logado']):
?>	
Olá <b><?php echo $_SESSION['login']?></b>, para sair do painel administrativo <a href="sair"><button type="button" class="btn btn-default">clique aqui.</button></a>
<br>
<?php
else:
header("Location: login");
endif;
?> <br>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
          <ul class="nav nav-justified">
            
            <li><a href="cate-cadastrar">Cadastrar categorias</a></li>
            <li><a href="cate">Editar categorias</a></li>
            <li><a href="material-cadastrar">Cadastrar Material</a></li>
            <li><a href="material">Editar Material</a></li>
            <li><a href="cliente">Clientes</a></li>
          </ul>
        </nav>

<h4>Cadastrar a categoria</h4>
<form action="cate-cadastrar-salvar" method="post">   
    <div class="form-group">
        <label>Nome da categoria: </label>        
        <input type="text" name="nome" class="form-control"> 
    </div>
   <button type="submit" class="btn btn-success">Cadastrar</button>
</form>